*** Settings ***
Library    SeleniumLibrary
Library    BuiltIn
Library    AngularJSLibrary

*** Variable ***

${SessionUserName}       xpath=//span[@class='sessionUserName']
${MenuItemHomePage}       xpath=//div[@class='headerQuickButtonText'][text()='Anasayfa']
${MenuItemMessages}       xpath=//div[@class='headerQuickButtonText'][text()='Mesajlar']
${MenuItemCompatibleMembers}       xpath=//div[@class='headerQuickButtonText'][text()='Uygun Üyeler']
${MenuItemFavorites}       xpath=//div[@class='headerQuickButtonText'][text()='Favorileriniz']
${MenuItemSearch}       xpath=//div[@class='headerQuickButtonText'][text()='Arama']
${MenuItemAccount}       xpath=//div[@class='headerQuickButtonText'][text()='Hesap']
${MenuItemNotifications}       xpath=//div[@class='headerQuickButtonText'][text()='Bildirimler']
${NotificationsText}       xpath=//div[@class='notification_header'][text()='Bildirimler']
${NotificationsTitle}       xpath=//div[@class='notificationTitle'][text()='Bildirimler']
${WelcomeTitle}       xpath=//span[@itemref='welcomeTitle'][text()='Hoşgeldin']
${MatchesTitle}       xpath=//div[@itemref='matchesTitle'][text()='Size Uygun Üyeler:']
${MembershipType}       xpath=//div[@class='paymentStatus']//span[text()='Üyelik Tipi']
${MembershipTypeStandard}       xpath=//span[@itemref='paymentStatus']//a[text()='Standart']
${ShortcutListItemMessages}       xpath=//a[@class='shortcutListItem'][text()='Mesajlar']
${ShortcutListItemSentMessages}       xpath=//a[@class='shortcutListItem'][text()='Giden Mesajlar']
${ShortcutListItemProfileVisits}       xpath=//a[@class='shortcutListItem'][text()='Profil Ziyaretleri']
${ShortcutListItemVisitedProfiles}       xpath=//a[@class='shortcutListItem'][text()='Profilini Ziyaret Ettikleriniz']
${ShortcutListItemCompatibleMembers}       xpath=//a[@class='shortcutListItem'][text()='Uygun Üyeler']
${ShortcutListItemBlinkingAtYou}       xpath=//a[@class='shortcutListItem'][text()='Size Göz Kırpan']
${ShortcutListItemBlinkedMembers}       xpath=//a[@class='shortcutListItem'][text()='Göz Kırptıklarınız']
${ShortcutListItemChoosingYouFavorite}       xpath=//a[@class='shortcutListItem'][text()='Sizi Favori Seçen']
${ShortcutListItemYourFavorites}       xpath=//a[@class='shortcutListItem'][text()='Favorileriniz:']
${HeaderShortcuts}       xpath=//div[@class='headerShortcutsText'][text()='Kısayollar']
${HeaderShortcutsNewMessage}       xpath=//div[@class='shortcutItemTitle'][text()='Yeni Mesaj:']
${HeaderShortcutsIncomingMessages}       xpath=//div[@class='shortcutItemTitle'][text()='Gelen Mesaj:']
${HeaderShortcutsSentMessages}       xpath=//div[@class='shortcutItemTitle'][text()='Giden Mesaj:']
${HeaderShortcutsDeletedMessages}       xpath=//div[@class='shortcutItemTitle'][text()='Silinen Mesaj:']
${HeaderShortcutsCompatibleMembers}       xpath=//div[@class='shortcutItemTitle'][text()='Uygun Üyeler']
${HeaderShortcutsBlinkingAtYou}       xpath=//div[@class='shortcutItemTitle'][text()='Size Göz Kırpan']
${HeaderShortcutsBlinkedMembers}       xpath=//div[@class='shortcutItemTitle'][text()='Göz Kırptıklarınız']
${HeaderShortcutsProfileVisits}       xpath=//div[@class='shortcutItemTitle'][text()='Profil Ziyaretleri']
${HeaderShortcutsVisitedProfiles}       xpath=//div[@class='shortcutItemTitle'][text()='Profilini Ziyaret Ettikleriniz']
${HeaderShortcutsChoosingYouFavorite}       xpath=//div[@class='shortcutItemTitle'][text()='Sizi Favori Seçen']
${HeaderShortcutsYourFavorites}       xpath=//div[@class='shortcutItemTitle'][text()='Favorileriniz:']
${HeaderShortcutsLogout}       xpath=//div[@class='shortcutItemTitle'][text()='Çıkış']
${BlockTitleShortcuts}       xpath=//div[@class='blockTitle'][text()='Kısayollar']
${BlockTitleGeneralRecommendations}       xpath=//div[@class='blockTitle'][text()='Genel Tavsiyeler']
${BlockTitleEditProfile}       xpath=//div[@class='blockTitle'][text()='Profil Düzenle']
${BlockTitleShortcutsSearch}       xpath=//div[@itemref='searchShortcutLink']//a[text()='Arama']
${BlockTitleShortcutsBlockedMembers}       xpath=//div[@itemref='blockedShortcutLink']//a[text()='Engellediğiniz Üyeler']
${BlockTitleShortcutsNotInterestedMembers}       xpath=//div[@itemref='notInterestedShortcutLink']//a[text()='İlgilenmediğiniz Üyeler']
${BlockTitleShortcutsProfilePreview}       xpath=//div[@itemref='profileEditShortcutLink']//a[text()='Profil Önizleme']
${BlockTitleShortcutsProfileEdit}       xpath=//div[@itemref='profileEditShortcutLink']//a[text()='Profil Düzenleme']
${BlockTitleShortcutsCharacterAnalysis}       xpath=//div[@itemref='characterAnalysisShortcutLink']//a[text()='Karakter Analizi']
${BlockTitleGeneralRecommendationsAboutYourMembership}       xpath=//div[@itemref='suggestionsMembership']//a[text()='Üyeliğiniz']
${BlockTitleGeneralRecommendationsPhotoSuggestions}       xpath=//div[@itemref='suggestionsPhotos']//a[text()='Fotoğraflarınız']
${BlockTitleGeneralRecommendationsMessageSuggestions}       xpath=//div[@itemref='suggestionsMessages']//a[text()='Mesajlarınız']
${BlockTitleGeneralRecommendationsSafetySuggestions}       xpath=//div[@itemref='suggestionsSafety']//a[text()='Güvenliğiniz İçin']
${BlockTitleEditProfileSocial}       xpath=//div[@itemref='editProfileSocial']//a[text()='Sosyal Ağ Bağlantıları']
${BlockTitleEditProfileCharacterAnalysis}       xpath=//div[@itemref='editProfileCharacterAnalysis']//a[text()='Karakter Analizi']
${BlockTitleEditProfileNotification}       xpath=//div[@itemref='editProfileNotification']//a[text()='Bildirim Ayarları']
${BlockTitleEditProfilePersonal}       xpath=//div[@itemref='editProfilePersonal']//a[text()='Kişisel Bilgiler']
